spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: tiger
    password: 123456
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
logging:
  level:
    root: info
    top.keir.mybatis: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # \u5168\u5C40\u903B\u8F91\u5220\u9664\u5B57\u6BB5\u540D
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C